# Generated by Django 6.0.2 on 2026-03-06 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='category',
            name='categories',
        ),
        migrations.AddField(
            model_name='tour',
            name='categories',
            field=models.ManyToManyField(related_name='tours', to='tourism.category'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tourism.person'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.person')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tourism.tour')),
            ],
        ),
    ]
