# Generated by Django 6.0.2 on 2026-03-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_of_facts', '0002_car_name_car_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adres', models.GenericIPAddressField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars_of_facts.car')),
            ],
        ),
    ]
