# Generated by Django 6.0.2 on 2026-03-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='drivers/')),
                ('birth_date', models.DateField()),
                ('car', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('license', models.BooleanField(default=True)),
            ],
        ),
    ]
