# Generated by Django 6.0.2 on 2026-03-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermodel',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='license',
            field=models.BooleanField(default=False),
        ),
    ]
