# Generated by Django 6.0.2 on 2026-03-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_drivermodel_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermodel',
            name='license',
            field=models.BooleanField(),
        ),
    ]
